### ISSUE TITLE
Is there a way to disable syntax highlighting for "mode" such as "x)"

### ISSUE THREAD

**Issue by flcong** [kdbinsidebrains/plugin#101]
Whenever I have something like `(0=count x)` in my script, the `x)` part is identified by a different syntax with different syntax highlighting.

I figured this seems to be related to q mode/k mode. Since I don't use this functionality at all, is there a quick way to let intellij NOT detecting this kind of syntax?

Currently, I have to add a space between `x` and `)` and then delete it so that the normal code syntax is applied to `x)`...

Thanks

**Comment by smklimenko** [comment]
I'm afraid I have no ideas what you mean but all shown as expected here:
with spaces
![image](https://github.com/user-attachments/assets/c51fa715-9f0d-4e2c-9d9d-631cb0d700e5)
or without spaces
![image](https://github.com/user-attachments/assets/0fc2dec6-171f-4030-92d4-29b5561f1534)

if you have any problems, please make sure you use the latest version.

**Comment by flcong** [comment]
![image](https://github.com/user-attachments/assets/161f563b-6b6e-484e-8c8b-16485995d967)
I mean this, using the Dracula Colorful theme in IntelliJ IDEA 2023.3.5 (Ultimate Edition).

In the default Light theme, it is as follows (though the distinction is not large):
![image](https://github.com/user-attachments/assets/519c3dee-2b0c-4ad1-b182-b04a653f3ac1)

It seems to be the same syntax style used by k mode:
![image](https://github.com/user-attachments/assets/b1102752-2f3b-4e91-a576-0ed9d272501b)

**Comment by smklimenko** [comment]
Should be fixed in version 5.8.3 once approved by JetBrains (usually 2-3 working days from now)

In a simple construction _(count x)_ it happens after each second space placed at the end of the line. It's related to IDEA syntax highlighting optimization when only last part of a text is passed to the Lexer analyzer and as _x)_ starts with start of line - it's wrongly identified as a MODE token.

Solution - check that previous char is start of file or new line. If not - it's a variable (_[a-zA-Z]_ can be only variable here).

**Comment by flcong** [comment]
Thanks!
