### ISSUE TITLE
KDB Inspector Problem

### ISSUE THREAD

**Issue by freeclb** [kdbinsidebrains/plugin#99]
you can always check all keys of a dict using command **key**:
**key .db.Ax**

Please make sure that you have symbol `290.130973 in the keys or copy the context of the keys here.

If I have dict with `290.130973 as a key:
![image](https://github.com/user-attachments/assets/6b595363-64ca-4fcf-bcb5-2910596fd7c9)

it's correctly shown in the Inspector for me:
![image](https://github.com/user-attachments/assets/79b6dfed-fed5-4cdf-b217-44f8a4866cce)

Feel free to reopen with more details

_Originally posted by @smklimenko in https://github.com/kdbinsidebrains/plugin/issues/98#issuecomment-2232690041_

**Comment by freeclb** [comment]
Actually .db.Ax like:
![image](https://github.com/user-attachments/assets/2a19eda7-9b3e-4d85-a74c-34a6e8ede573)
and key is symbol， KDB Inspector says structure can't be loaded.

**Comment by smklimenko** [comment]
In this case .db.Ax is not a dictionary but namespace: https://code.kx.com/q/basics/syntax/#names-and-namespaces

Namespace can't have dot in names as dot is a separator and system functions \a, \f, \v (https://code.kx.com/q/basics/syscmds/#f-functions) don't work herecan be used to analyze the namespace name _.db.Ax.290.130974_ is treated as 4 separate inner namespaces:
db
 Ax
  290
    130974

In result, even formally, that's fine from Q point of data types but as some system functions don't work - the Inspector fails to show anything here.

This won't be fixed on my side. Once you use dictionary type for .db.Ax rather than namespace type for this variable the Inspector will work with no issues.

I even can't imagine how you create such namespace structure because when you do something like but maybe it's better to revise your code here as it potentially can lead to more critical issues.

**Comment by smklimenko** [comment]
ok, probably I know how to fix that. Not very correct but anyway, should work somehow

**Comment by smklimenko** [comment]
Fixed in 5.8.2 once available in JetBrains Marketplace

**Comment by freeclb** [comment]
Thanks!
